### ISSUE TITLE
Game set graphic missing letters

### ISSUE THREAD

**Issue by 88ws6** [GhostlyDark/SSB-Reloaded#1]
![Super Smash Bros  (USA)-240501-212502](https://github.com/GhostlyDark/SSB-HD/assets/126357486/8dcdfe36-581c-43f1-a205-1f087c937ecb)

When finishing a match the game set graphic just reads GAM. The E isn't hidden behind the fountain effect, just how the screen shot came out. Easy way to fix this?

**Comment by GhostlyDark** [comment]
The texture pack isn't at fault here. It could be some emulator/graphics plugin setting and I believe this could be caused by the widescreen hack (GLideN64 with "try to adjust"?).

![image](https://github.com/GhostlyDark/SSB-HD/assets/31742919/0e7013fa-ac24-4e3c-a0f0-edcb9e732ee6)

**Comment by 88ws6** [comment]
Thanks! I am running GLideN64 through Retroarch 1.15 with the Mupen64Plus-Next core. Tried to put it in native 4x3 mode and still same issue. I'll have to keep trying other GLide settings and hope I find the culprit.
